services:
  - type: web
    name: vite-frontend
    runtime: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"